Repository GameTactic/Room, pull requests merged in 2020-05, with the labels that each got.

#196 Feature/193 WG API to Proxy + Refactor Room State + Implement basic Authentication + Implement premature code for Socket.io
  .env
  .eslintrc.js
  src/App.vue
  src/components/TheCanvas.vue
  src/components/TheEntityPanel.vue
  src/components/entity-panel/games/Wows.vue
  src/components/navigation/LoginCard.vue
  src/components/navigation/TheUserMenu.vue
  src/games/wows/api.ts
  src/plugins/vuetify.ts
  src/store/index.ts
  src/store/modules/authentication.ts
  src/store/modules/canvas.ts
  src/store/modules/room.ts
  src/store/modules/socket.ts
  src/store/modules/types.d.ts
  src/tools/Circle.ts
  src/tools/Erase.ts
  src/tools/FreeDraw.ts
  src/tools/Line.ts
  src/tools/Move.ts
  src/tools/Ping.ts
  src/tools/Ruler.ts
  src/tools/Text.ts
  src/types/Games/Index.ts
  src/types/Games/Wows.ts
  src/views/Room.vue
Labels: enhancement, frontend

#204 Security/10052020
  yarn.lock
Labels: dependencies

#187 Feature/15 login
  src/App.vue
  src/components/navigation/LoginCard.vue
  src/components/navigation/TheUserMenu.vue
  src/components/navigation/login/ProviderBlock.vue
  src/plugins/vuetify.ts
  src/store/modules/authentication.ts
  src/store/modules/types.ts
  src/util/ProvidersUtil.ts
  src/util/TypeUtils.ts
Labels: enhancement
