Repository GameTactic/Room, pull requests merged in 2020-03, with the labels that each got.

#97 Fix circle
  src/tools/Circle.ts
  src/tools/FreeDraw.ts
Labels: bug, enhancement

#98 Feature/95 entity settings flex box mock up
  src/assets/scss/_variables.scss
  src/assets/wot-icon.png
  src/assets/wows-icon.png
  src/components/TheEntityPanel.vue
  src/components/TheToolPanel.vue
  src/plugins/vuetify.ts
Labels: enhancement

#104 Add sentry support
  package.json
  src/main.ts
  src/plugins/sentry.ts
  yarn.lock
Labels: enhancement

#107 Add sentry support (#104)
  package.json
  src/main.ts
  src/plugins/sentry.ts
  yarn.lock
Labels: enhancement

#106 Feature/55 completed circle
  src/components/TheToolPanel.vue
  src/components/canvas-tools/templates/Circle.vue
  src/components/canvas-tools/templates/Freedraw.vue
  src/components/canvas-tools/templates/template-tools/ColourPicker.vue
  src/components/canvas-tools/templates/template-tools/SizePicker.vue
  src/plugins/vuetify.ts
  src/store/modules/tools.ts
  src/tools/Circle.ts
  src/tools/Tool.ts
  src/types/Canvas.d.ts
Labels: enhancement

#109 91 - Canvas Tools - Step 1
  src/assets/cursor/circle.png
  src/assets/cursor/eraser.png
  src/assets/cursor/pen.png
  src/components/TheCanvas.vue
Labels: frontend

#101 [WIP] Added straight line functionality.
  src/components/TheToolPanel.vue
  src/components/canvas-tools/templates/Circle.vue
  src/components/canvas-tools/templates/Line.vue
  src/components/canvas-tools/templates/template-tools/SizePicker.vue
  src/plugins/vuetify.ts
  src/store/modules/tools.ts
  src/tools/Circle.ts
  src/tools/Line.ts
  src/tools/Tool.ts
  src/tools/shapes/LineCreator.ts
  src/tools/shapes/Shape.ts
  src/types/Canvas.d.ts
Labels: enhancement

#111 Fixed bug where parameters werent updated
  src/tools/Line.ts
  src/tools/shapes/LineCreator.ts
Labels: enhancement

#113 Added sendToWebSocket to tool interface
  src/tools/Circle.ts
  src/tools/Erase.ts
  src/tools/FreeDraw.ts
  src/tools/Line.ts
  src/tools/Ping.ts
  src/tools/Ruler.ts
  src/tools/Tool.ts
Labels: enhancement

#119 Implement eraser
  src/tools/Circle.ts
  src/tools/Erase.ts
  src/tools/FreeDraw.ts
  src/tools/Line.ts
  src/tools/Ping.ts
  src/tools/Ruler.ts
  src/tools/Tool.ts
  src/tools/shapes/CircleCreator.ts
  src/tools/shapes/FreedrawCreator.ts
  src/tools/shapes/LineCreator.ts
  src/tools/shapes/PingCreator.ts
  src/tools/shapes/RulerCreator.ts
Labels: enhancement

#122 Merge #114 #119 #120
  src/components/TheCanvas.vue
  src/components/canvas-tools/templates/Circle.vue
  src/components/canvas-tools/templates/Freedraw.vue
  src/components/canvas-tools/templates/Line.vue
  src/components/canvas-tools/templates/template-tools/ColourPicker.vue
  src/store/modules/canvas.ts
  src/store/modules/tools.ts
  src/tools/Circle.ts
  src/tools/Erase.ts
  src/tools/FreeDraw.ts
  src/tools/Line.ts
  src/tools/Ping.ts
  src/tools/Ruler.ts
  src/tools/Tool.ts
  src/tools/shapes/CircleCreator.ts
  src/tools/shapes/FreedrawCreator.ts
  src/tools/shapes/LineCreator.ts
  src/tools/shapes/PingCreator.ts
  src/tools/shapes/RulerCreator.ts
  src/types/Canvas.d.ts
Labels: enhancement

#125 Implemented undo and redo
  src/components/TheCanvas.vue
  src/components/TheToolPanel.vue
  src/components/canvas-tools/RedoContainer.vue
  src/components/canvas-tools/UndoContainer.vue
  src/event-bus.ts
  src/plugins/vuetify.ts
  src/store/modules/canvas.ts
  src/store/modules/tools.ts
  src/tools/Circle.ts
  src/tools/Erase.ts
  src/tools/FreeDraw.ts
  src/tools/Line.ts
  src/tools/Ping.ts
  src/tools/Ruler.ts
  src/tools/Tool.ts
  src/tools/UndoRedo.ts
  src/tools/shapes/CircleCreator.ts
  src/tools/shapes/FreedrawCreator.ts
  src/tools/shapes/LineCreator.ts
  src/tools/shapes/PingCreator.ts
  src/tools/shapes/RulerCreator.ts
  src/types/Canvas.ts
Labels: enhancement
