Repository GameTactic/Room, pull requests merged in 2020-04, with the labels that each got.

#166 Feature/137 tactic tools bar
  src/App.vue
  src/assets/scss/_variables.scss
  src/components/TheEntityPanel.vue
  src/components/canvas-tools/ToolContainer.vue
  src/components/entity-panel/sections/TheCreateEntity.vue
  src/components/navigation/TheCanvasTools.vue
  src/components/navigation/TheNavLarge.vue
  src/components/navigation/TheNavSmall.vue
  src/components/navigation/TheRoomMenu.vue
  src/components/navigation/TheUserMenu.vue
  src/plugins/vuetify.ts
Labels: frontend

#167 Made improvements to the canvastools
  src/Util/HandleAddText.ts
  src/Util/HandleMouseUp.ts
  src/Util/HandleRenderShapes.ts
  src/Util/HandleSocketMessage.ts
  src/Util/HandleUndoRedo.ts
  src/Util/PointerEventMapper.ts
  src/components/TheCanvas.vue
  src/components/canvas-tools/RedoContainer.vue
  src/components/canvas-tools/ToolContainer.vue
  src/components/canvas-tools/UndoContainer.vue
  src/components/canvas-tools/templates/Circle.vue
  src/components/canvas-tools/templates/Line.vue
  src/components/canvas-tools/templates/Ruler.vue
  src/components/canvas-tools/templates/template-tools/ColourPicker.vue
  src/components/canvas-tools/templates/template-tools/ColourPickerTransparency.vue
  src/mixins/CanvasTools.ts
  src/store/modules/tools.ts
  src/tools/Circle.ts
  src/tools/Erase.ts
  src/tools/FreeDraw.ts
  src/tools/Line.ts
  src/tools/Ruler.ts
  src/tools/Text.ts
  src/tools/Tool.ts
  src/tools/UndoRedo.ts
  src/tools/shapes/CircleCreator.ts
  src/tools/shapes/RulerCreator.ts
  src/tools/shapes/Shape.ts
Labels: enhancement

#168 Added tooltip to all buttons, modified logo size
  src/assets/scss/_variables.scss
  src/components/TheEntityPanel.vue
  src/components/navigation/TheCanvasTools.vue
  src/components/navigation/TheNavLarge.vue
  src/components/navigation/TheNavSmall.vue
  src/components/navigation/TheRoomMenu.vue
  src/components/navigation/TheUserMenu.vue
Labels: enhancement, frontend

#171 Feature/13 map dimensions
  src/App.vue
  src/Util/HandleAddText.ts
  src/Util/HandleRenderShapes.ts
  src/Util/PointerEventMapper.ts
  src/assets/scss/_variables.scss
  src/components/TheCanvas.vue
  src/components/TheToolPanel.vue
  src/components/canvas-tools/RedoContainer.vue
  src/components/canvas-tools/ToolContainer.vue
  src/components/canvas-tools/UndoContainer.vue
  src/components/navigation/TheCanvasTools.vue
  src/components/navigation/TheNavLarge.vue
  src/components/navigation/TheNavSmall.vue
  src/store/index.ts
  src/store/modules/canvas.ts
  src/store/modules/stage.ts
  src/store/modules/tools.ts
  src/tools/Circle.ts
  src/tools/Erase.ts
  src/tools/FreeDraw.ts
  src/tools/Line.ts
  src/tools/Move.ts
  src/tools/Ping.ts
  src/tools/Ruler.ts
  src/tools/Text.ts
  src/tools/Tool.ts
  src/tools/shapes/CircleCreator.ts
  src/tools/shapes/FreedrawCreator.ts
  src/tools/shapes/LineCreator.ts
  src/tools/shapes/PingCreator.ts
  src/tools/shapes/RulerCreator.ts
  src/tools/shapes/Shape.ts
  src/tools/shapes/TextCreator.ts
  src/tools/util/MoveCanvas.ts
  src/util/HandleCanvas.ts
  src/util/HandleMouseUp.ts
  src/util/HandleRenderShapes.ts
  src/util/HandleSocketMessage.ts
  src/util/HandleUndoRedo.ts
  src/util/PointerEventMapper.ts
  src/views/Room.vue
Labels: enhancement

#173 Fix/responsive mobile
  src/assets/scss/_variables.scss
  src/components/TheCanvas.vue
  src/components/TheEntityPanel.vue
  src/components/TheToolPanel.vue
  src/components/canvas-tools/ToolContainer.vue
  src/components/canvas-tools/templates/Circle.vue
  src/components/canvas-tools/templates/Freedraw.vue
  src/components/canvas-tools/templates/Line.vue
  src/components/canvas-tools/templates/Text.vue
  src/components/navigation/TheNavLarge.vue
  src/components/navigation/TheNavSmall.vue
  src/components/navigation/TheRoomMenu.vue
  src/components/navigation/TheUserMenu.vue
  src/views/Room.vue
Labels: enhancement

#195 Implement MVP1 - Nav. Remove shadows (GameTactic#189)
  src/components/navigation/TheNavLarge.vue
  src/components/navigation/TheNavSmall.vue
Labels: enhancement
